all: broadcast-example unicast-sender unicast-receiver
APPS=servreg-hack
CONTIKI=../../..

CLFAGS=-I/home/hartung/git/contiki-inga/examples/ipv6/simple-udp-rpl/
PROJECT_SOURCEFILES=marker.c

CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
